# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='archivo_csv',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads'),
        ),
    ]
